---

 - name: setup client ntp chronyd config 
   ansible.builtin.template:
     src: templates/rhel8_client_rsyslog.conf.j2
     dest: /etc/rsyslog.conf
     owner: root
     group: root
     mode: '0644'

 - name: restart of rsyslog
   service:
     name: rsyslog
     state: restarted

